vayu: dolby: Fix bluetooth permissions
* E AndroidRuntime:
 java.lang.IllegalStateException: Signature|privileged permissions not in
 privileged permission allowlist: {com.motorola.dolby.dolbyui
 (/system_ext/priv-app/MotoDolbyDax3):
 android.permission.BLUETOOTH_PRIVILEGED}   E/AndroidRuntime(5644): Caused by:
 java.lang.SecurityException: Neither user 10390 nor current process has
 android.permission.BLUETOOTH_PRIVILEGED

Reference to https://github.com/raystef66/vendor_xiaomi_cepheus/commit/e7f5ecd1dff407b8cc89a7519530f423d4d2d8e4

Signed-off-by: bagaskara815 <bagaskara815@gmail.com>